version: "3.6"

services:
  # run it with: `docker-compose run --rm ruby`
  ruby:
    command: /bin/bash
    build: .
    volumes:
      - ${PWD}:/${PWD}:cached
      - ~/Google Drive/boostnotes:${PWD}/notes
    environment:
      # Add environment variables
      LANG: C.UTF-8
    working_dir: ${PWD}
