version: "3.6"

services:
  # run it with: `docker-compose run --rm --service-ports ruby`
  ruby:
    command: /bin/bash
    build: .
    volumes:
      - ${PWD}:/app:cached
    ports:
      - "12345:12345"
    environment:
      # Add environment variables
      LANG: C.UTF-8
    working_dir: /app
